// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipycssevroitrjsjkgfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlweWNzc2V2cm9pdHJqc2prZ2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDQzNjksImV4cCI6MjA1NjkyMDM2OX0.IZwmj06mU6dAqqcS-ogkjYeZuZNuQwRIkmsLnDpr-WY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);